module.exports = {"code":200,"yhxq_variable_data":{
    "config":[{
        "url":"https://gitee.com/soy-tool/app-script/raw/master/app_yhxq.js",
        "update":false,
        "notice":false
    }],
    "user_data":[{
        "token":"请求头上的Authorization值",
        "Withdrawal":true,
        "Withdrawal_Time":12:29:00,
        "Feed":true代表喂养,
        "Hoe":1,
        "UA":"请求UA头,请求头的User-Agent值(选填)"
    },{
        "token":"多号如上,没有就删除,否则报错",
        "Withdrawal":多号如上,没有就删除,否则报错,
        "Withdrawal_Time":多号如上,没有就删除,否则报错,
        "Feed":多号如上,没有就删除,否则报错,
        "Hoe":(拔萝卜次数,每天可免费一次,默认填1),
        "UA":"多号如上,没有就删除,否则报错"
    },{
        "token":"多号如上,没有就删除,否则报错",
        "Withdrawal":多号如上,没有就删除,否则报错,
        "Withdrawal_Time":多号如上,没有就删除,否则报错,
        "Feed":多号如上,没有就删除,否则报错,
        "Hoe":(拔萝卜次数,每天可免费一次,默认填1),
        "UA":"多号如上,没有就删除,否则报错"
    }
    
]}}